version:
  name: velociraptor
  version: 0.72.4
  commit: d568709b
  build_time: "2024-07-04T14:12:22Z"
  install_time: 1721222668
  compiler: go1.20.6
Client:
  server_urls:
  - https://velociraptor.rbnetto.dev/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQNTUPlqZgcOyyGL1ZB0gd8TANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwNzE3MTMzODQwWhcNMzQw
    NzE1MTMzODQwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDi2xCyIkEHjBz7H1hAxOEFvK/ZXu/B4Us4
    8c6IxWeAq8iTHf1T1dHlHplDqEV104zZrOhKun+uwKzHobj+Rxmxa5F7KisWYYhR
    frYX5pn3SRI0wzzKJpPzXFHKRMTFKlkNdFnL/SttEPZWryCe5OjI3S0n76zUzquK
    5vq6aodJl9By7Q7thYfVxLh59rPXTFyrX4yHRCm4gr2VSMz4VQ3Si7B6d3Ps2ymu
    TCZlFqZokqIviq6M79hxlenG62N7jp+aNmbuGpptkYlzZiq/ims7TxXVVK5H4u90
    n7HtzvsFvQAHySNp8yE5kw/SCzZ7s5SR61pbsDiuCL5/2bXOkvkLAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSC6uCVZDJDmA7jaLLGAuE9GDp2
    kTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEACkEzGC0cWQnihk4y8mMT3/F6JrQV8XzUib56mMh544Oc
    uoR+0rVePWZLWSC4prJq+/QE5zyoeE9iEQxMGYwsIpDY/JMRPrC6m9sNgreuoHst
    FPql/iuYOVppoVjhxXkZj1qDsfS0OFQandvprUxX2QJB16RtsvGeWK3tl0cz4g3d
    NkVShZVD9YtJuYOvRirb06vwsajvGTku2VXOh3EifwdIibU6AsTWzvH2YbCMlNsG
    jZPl9vRfmgMGyR+oVc260x2EW5WgsEe9wVRyPzoc+VskXo/6h4/PAzlFgf151xSk
    zlb7OgVDnCmgzbZMwu6tKERIJyfOY6i0i8q6jOlnIg==
    -----END CERTIFICATE-----
  nonce: UJz2UXPiuUw=
  writeback_darwin: /etc/Velociraptor/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.72.4
    commit: d568709b
    build_time: "2024-07-04T14:12:22Z"
    install_time: 1721222668
    compiler: go1.20.6
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
